#!/bin/sh

set -e

here=`pwd`
target=`dirname "$filename"`
cd $target
target_dir=`pwd`
cd "$here"

while [ ! -f "$target_dir/.build" -a "$target_dir" != "/" ];
do
    target_dir=`dirname "$target_dir"`
done

if [ -f "$target_dir/.build" ]; then
    cd "$target_dir"
    exec ./.build $@
else
    make $@
fi
